title: minoru's Emacs Configuration
remote_theme: rundocs/jekyll-rtd-theme

# Theme settings:
site_author: minoru yamada
repo_url: "https://github.com/minorugh/emacs.d/"

markdown_extensions:
    # コードハイライトの設定
    - codehilite:
        pygments_style: vim

edit_on_github: false
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: false
hljs_style: github-gist
