title: minoru's Emacs Configuration
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
# remote_theme: readthedocs/sphinx-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme
# remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: minoru yamada
repo_url: "https://github.com/minorugh/emacs.d/"
edit_on_github: false
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: false
hljs_style: github-gist
