title: minoru's Emacs Configuration
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: minorugh
repo_url: "https://github.com/minorug/emacs.d"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: nil
hljs_style: github-gist
